select cli_codigo, cli_nome from clientes where cli_sexo='M' and CLI_STATUS='A'or CLI_status='I';
ALTER  TABLE CLIENTES ADD CLI_STATUS2 CHAR(1) NOT NULL;
DESC CLIENTES;
ALTER TABLE CLIENTES DROP CLI_STATUS2;
DESC CLIENTES ;
UPDATE CLIENTES SET CLI_STATUS='I' WHERE CLI_CODIGO=3 OR CLI_CODIGO=5; 
SELECT CLI_CODIGO, CLI_STATUS FROM CLIENTES;
SELECT * FROM MUNICIPIOS;
DELETE FROM MUNICIPIOS WHERE MUN_CODIGO = 105 ; 
SELECT * FROM MUNICIPIOS;









